services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${DATA_PATH:-/mnt/usb/dashops}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  json_exporter:
    build: ./json_exporter
    container_name: json_exporter
    restart: unless-stopped
    environment:
      - THINGPARK_CLIENT_ID=${THINGPARK_CLIENT_ID}
      - THINGPARK_CLIENT_SECRET=${THINGPARK_CLIENT_SECRET}
    volumes:
      - ./json_exporter/config.yml.template:/config.yml.template:ro
    ports:
      - "7979:7979"
    networks:
      - monitoring

  backup:
    image: alpine
    container_name: backup
    volumes:
      - prometheus_data:/prometheus
      - grafana_data:/grafana
      - /mnt/usb:/backup
    command: sh
    networks:
      - monitoring
#    stdin_open: true
#    tty: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ${DATA_PATH:-/mnt/usb/dashops}/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
